import esbuild from "esbuild";
import path from "node:path";
import process from "process";
import builtins from "builtin-modules";
import { fileURLToPath } from "node:url";
import {
  PLUGIN_CATALOG,
  validatePluginCatalog,
} from "./scripts/plugin-catalog.mjs";
import { buildCompanionWorker } from "./scripts/build-companion-worker.mjs";

const production = process.argv[2] === "production";
const repoRoot = path.dirname(fileURLToPath(import.meta.url));

await validatePluginCatalog(repoRoot);
await buildCompanionWorker(repoRoot);

const contexts = await Promise.all(
  PLUGIN_CATALOG.map((plugin) =>
    esbuild.context({
      absWorkingDir: repoRoot,
      banner: {
        js: "/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n*/",
      },
      entryPoints: [plugin.entry],
      bundle: true,
      external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
        ...(plugin.desktopOnly
          ? [
              "node:*",
              ...builtins.map((name) => `node:${name}`),
              // `builtin-modules` versions differ on whether this subpath is
              // enumerated. Keep the desktop package-store boundary explicit.
              "node:fs/promises",
            ]
          : []),
      ],
      format: "cjs",
      target: "es2018",
      logLevel: "info",
      sourcemap: production ? false : "inline",
      treeShaking: true,
      loader: {
        ".py": "text",
        ".txt": "text",
        ".html": "text",
        ".json": "text",
      },
      outfile: plugin.outfile,
      minify: production,
    }),
  ),
);

if (production) {
  await Promise.all(contexts.map((context) => context.rebuild()));
  await Promise.all(contexts.map((context) => context.dispose()));
} else {
  await Promise.all(contexts.map((context) => context.watch()));
}
