import esbuild from "esbuild";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "process";
import builtins from "builtin-modules";
import { fileURLToPath } from "node:url";
import {
  PLUGIN_CATALOG,
  validatePluginCatalog,
} from "./scripts/plugin-catalog.mjs";
import { buildCompanionWorker } from "./scripts/build-companion-worker.mjs";
import { buildCompanionAssets } from "./scripts/build-companion-assets.mjs";
import { validateWorkspaceLinks } from "./scripts/check-workspace-links.mjs";

const production = process.argv[2] === "production";
const repoRoot = path.dirname(fileURLToPath(import.meta.url));

// Before anything is bundled: a node_modules borrowed from another checkout —
// or missing here entirely, so the resolution walk climbs into one — would
// silently bundle every workspace module twice.
await validateWorkspaceLinks(repoRoot);
await validatePluginCatalog(repoRoot);
await buildCompanionWorker(repoRoot);
// After the worker: the sibling companion-assets.json artifact embeds the
// freshly built standalone worker, and the generated manifest that main.js
// bundles must carry the hashes of exactly this build.
await buildCompanionAssets(repoRoot);

const contexts = await Promise.all(
  PLUGIN_CATALOG.map((plugin) =>
    esbuild.context({
      absWorkingDir: repoRoot,
      banner: {
        js: "/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n*/",
      },
      entryPoints: [plugin.entry],
      bundle: true,
      external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
        ...(plugin.desktopOnly
          ? [
              "node:*",
              ...builtins.map((name) => `node:${name}`),
              // `builtin-modules` versions differ on whether this subpath is
              // enumerated. Keep the desktop package-store boundary explicit.
              "node:fs/promises",
            ]
          : []),
      ],
      format: "cjs",
      target: "es2018",
      logLevel: "info",
      sourcemap: production ? false : "inline",
      treeShaking: true,
      metafile: production,
      legalComments: production ? "none" : "inline",
      loader: {
        ".py": "text",
        ".txt": "text",
        ".html": "text",
        ".json": "text",
      },
      outfile: plugin.outfile,
      minify: production,
    }),
  ),
);

if (production) {
  const results = await Promise.all(
    contexts.map((context) => context.rebuild()),
  );
  await writeProductionMetafile(repoRoot, results);
  await Promise.all(contexts.map((context) => context.dispose()));
} else {
  await Promise.all(contexts.map((context) => context.watch()));
}

async function writeProductionMetafile(root, results) {
  const metafile = results[0]?.metafile;
  if (!metafile) return;
  const cacheDir = path.join(root, ".cache");
  await mkdir(cacheDir, { recursive: true });
  await writeFile(
    path.join(cacheDir, "esbuild-metafile.json"),
    JSON.stringify(metafile),
    "utf8",
  );
}
