import assert from "node:assert/strict";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test, { after, before } from "node:test";

import {
  runInteractiveCliProgram,
  type InteractiveCliRunResult,
} from "../e2e/fixtures/interactiveCliDriver";

/**
 * Behavioural proof for the adaptive CLI driver, against real child processes.
 *
 * The unit tests next door pin the decision function; these run whole programs
 * so the driver's *timing* is exercised too: a delayed start, a prompt split
 * across two writes, a read with no prompt at all. Every program here is
 * generated by this file, so nothing depends on one model's transcript.
 *
 * The corpus is deliberately two-sided. Five programs are correct and must be
 * driven to a win; four are broken in a way a real generated program is broken
 * (never accepts an answer, never reads stdin, never exits, crashes on start)
 * and must be *rejected*. A driver that passed everything would be worthless
 * as an acceptance instrument, so the broken half is the load-bearing half.
 *
 * The games are Node programs rather than Python ones so the corpus can never
 * silently skip; tests/interactiveCliDriverPython.test.ts mirrors two of them
 * on the interpreter the delivery lane actually runs.
 */

// Line-oriented stdin plus an input() lookalike: the prompt is written without
// a trailing newline, and EOF ends the program the way Python's EOFError does.
const PRELUDE = `
import { createInterface } from "node:readline";
const rl = createInterface({ input: process.stdin, crlfDelay: Infinity });
const iterator = rl[Symbol.asyncIterator]();
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
const say = (line) => console.log(line);
const write = (text) => process.stdout.write(text);
async function ask(text) {
  if (text) write(text);
  const next = await iterator.next();
  if (next.done) {
    console.error("Traceback (most recent call last):");
    console.error("EOFError: EOF when reading a line");
    process.exit(1);
  }
  return String(next.value).trim();
}
function done(code) {
  process.exit(code);
}
`;

/** A plain, immediately-responsive game. Answering "y" to play-again exits 3. */
const GAME_CLASSIC = `
say("Welcome to the Number Guessing Game!");
say("I'm thinking of a number between 1 and 100.");
const target = 42;
let attempts = 0;
for (;;) {
  const raw = await ask("Your guess: ");
  attempts += 1;
  const value = Number.parseInt(raw, 10);
  if (!Number.isInteger(value)) { say("Please enter a number."); continue; }
  if (value > target) { say("Too high!"); continue; }
  if (value < target) { say("Too low!"); continue; }
  break;
}
say("Correct! You guessed it in " + attempts + " tries.");
const again = (await ask("Play again? (y/n): ")).toLowerCase();
if (again === "y") { say("A second round was not requested."); done(3); }
say("Thanks for playing!");
done(0);
`;

/**
 * Slow start, a name prompt, a difficulty menu that *selects* the range, and a
 * small 1-10 range. Every entered line costs an attempt, so a driver that
 * spends its budget on a range the program never offered loses a winnable
 * game.
 */
const GAME_DELAYED_MENU = `
await sleep(900);
const name = await ask("Enter your name: ");
say("Hello, " + name + "!");
let low = 1;
let high = 100;
const choice = (await ask("Difficulty [easy/medium/hard]: ")).toLowerCase();
if (choice === "easy" || choice === "1") { low = 1; high = 10; }
else if (choice === "hard" || choice === "3") { low = 1; high = 1000; }
const target = 7;
say("I'm thinking of a number between " + low + " and " + high + ".");
let attempts = 0;
while (attempts < 6) {
  const raw = await ask("Your guess: ");
  attempts += 1;
  const value = Number.parseInt(raw, 10);
  if (!Number.isInteger(value) || value < low || value > high) { say("Out of range."); continue; }
  if (value > target) { say("Too high!"); continue; }
  if (value < target) { say("Too low!"); continue; }
  say("Correct! You win in " + attempts + " tries.");
  done(0);
}
say("Out of attempts! The number was " + target + ".");
done(2);
`;

/** Reads its first line with no prompt at all: the driver sees pure silence. */
const GAME_SILENT_START = `
const name = await ask("");
say("Hello, " + name + "!");
say("I'm thinking of a number between 1 and 1000.");
const target = 777;
let attempts = 0;
while (attempts < 12) {
  const raw = await ask("Your guess: ");
  attempts += 1;
  const value = Number.parseInt(raw, 10);
  if (!Number.isInteger(value)) {
    console.error("Traceback (most recent call last):");
    console.error("ValueError: invalid literal for int() with base 10");
    done(1);
  }
  if (value > target) { say("Too high!"); continue; }
  if (value < target) { say("Too low!"); continue; }
  say("Correct! You win in " + attempts + " tries.");
  done(0);
}
say("Out of attempts! The number was " + target + ".");
done(2);
`;

/**
 * Banner first, then a pause, then the real question. Answering the banner as
 * though it were the question desynchronises the whole run: the name slot eats
 * a number and the announced range is never read.
 */
const GAME_CHUNKED_PROMPT = `
say("Welcome to the Number Guessing Game!");
await sleep(400);
const name = await ask("Enter your name: ");
say("Hello, " + name + "!");
say("I'm thinking of a number between 1 and 1000.");
const target = 777;
let attempts = 0;
while (attempts < 12) {
  const raw = await ask("Your guess: ");
  attempts += 1;
  const value = Number.parseInt(raw, 10);
  if (!Number.isInteger(value)) {
    console.error("Traceback (most recent call last):");
    console.error("ValueError: invalid literal for int() with base 10");
    done(1);
  }
  if (value > target) { say("Too high!"); continue; }
  if (value < target) { say("Too low!"); continue; }
  say("Correct! You win in " + attempts + " tries.");
  done(0);
}
say("Out of attempts! The number was " + target + ".");
done(2);
`;

/** Replays by itself, on a smaller range, without asking permission. */
const GAME_TWO_ROUNDS = `
const rounds = [
  { low: 1, high: 100, target: 42, limit: 12 },
  { low: 1, high: 20, target: 13, limit: 10 },
];
say("Welcome to the Number Guessing Game!");
say("I'm thinking of a number between 1 and 100.");
for (let index = 0; index < rounds.length; index += 1) {
  const round = rounds[index];
  let attempts = 0;
  let won = false;
  while (attempts < round.limit) {
    const raw = await ask("Your guess: ");
    attempts += 1;
    const value = Number.parseInt(raw, 10);
    if (!Number.isInteger(value) || value < round.low || value > round.high) { say("Out of range."); continue; }
    if (value > round.target) { say("Too high!"); continue; }
    if (value < round.target) { say("Too low!"); continue; }
    won = true;
    break;
  }
  if (!won) { say("Out of attempts! The number was " + round.target + "."); done(2); }
  const next = rounds[index + 1];
  if (next) {
    say("Correct!");
    say("Round " + (index + 2) + ": I'm thinking of a number between " + next.low + " and " + next.high + ".");
  }
}
say("You win! Thanks for playing.");
done(0);
`;

/** Broken: no answer is ever accepted, so the run must end bounded and red. */
const GAME_NEVER_WINS = `
say("I'm thinking of a number between 1 and 100.");
for (;;) {
  await ask("Your guess: ");
  say("Too low!");
}
`;

/** Broken: claims a win without ever reading a line. */
const GAME_IGNORES_STDIN = `
say("Correct! You win! Congratulations.");
done(0);
`;

/** Broken: prompts, then neither reads nor exits. */
const GAME_HANGS = `
write("Your guess: ");
setInterval(() => {}, 1000);
`;

/** Broken: dies on start, the way an import error or a syntax slip does. */
const GAME_CRASHES = `
console.error("Traceback (most recent call last):");
console.error("ZeroDivisionError: division by zero");
done(1);
`;

let workspace = "";

before(async () => {
  workspace = await mkdtemp(path.join(tmpdir(), "cli-driver-programs-"));
});

after(async () => {
  if (workspace) await rm(workspace, { recursive: true, force: true });
});

async function play(
  name: string,
  body: string,
  options: { timeoutMs?: number } = {},
): Promise<InteractiveCliRunResult> {
  const file = path.join(workspace, `${name}.mjs`);
  await writeFile(file, `${PRELUDE}\n${body}`, "utf8");
  return runInteractiveCliProgram({
    command: process.execPath,
    args: [file],
    cwd: workspace,
    timeoutMs: options.timeoutMs ?? 30_000,
  });
}

function describe(result: InteractiveCliRunResult): string {
  return JSON.stringify({
    exitCode: result.exitCode,
    timedOut: result.timedOut,
    responses: result.responses,
    tail: result.stdout.trim().split(/\r?\n/u).slice(-4),
    stderr: result.stderr.trim().slice(0, 200),
  });
}

test("a plain guessing game is played to a win and declines a second round", async () => {
  const result = await play("classic", GAME_CLASSIC);
  assert.equal(result.timedOut, false, describe(result));
  assert.equal(result.exitCode, 0, describe(result));
  assert.match(result.stdout, /Correct! You guessed it in \d+ tries\./u);
  assert.match(result.stdout, /Thanks for playing!/u);
});

test("a slow-starting game with a difficulty menu is played on the range it selected", async () => {
  const result = await play("delayed-menu", GAME_DELAYED_MENU);
  assert.equal(result.timedOut, false, describe(result));
  assert.equal(result.exitCode, 0, describe(result));
  assert.match(result.stdout, /Correct! You win in \d+ tries\./u);
  assert.doesNotMatch(result.stdout, /Out of attempts!/u, describe(result));
});

test("a game that reads its first line with no prompt is still played on its own range", async () => {
  const result = await play("silent-start", GAME_SILENT_START);
  assert.equal(result.timedOut, false, describe(result));
  assert.equal(result.exitCode, 0, describe(result));
  assert.match(result.stdout, /Correct! You win in \d+ tries\./u);
});

test("a prompt split across two writes is answered as one question", async () => {
  const result = await play("chunked-prompt", GAME_CHUNKED_PROMPT);
  assert.equal(result.timedOut, false, describe(result));
  assert.equal(result.exitCode, 0, describe(result));
  assert.match(result.stdout, /Hello, Player!/u, describe(result));
  assert.match(result.stdout, /Correct! You win in \d+ tries\./u);
});

test("a game that replays itself on a new range is won twice", async () => {
  const result = await play("two-rounds", GAME_TWO_ROUNDS);
  assert.equal(result.timedOut, false, describe(result));
  assert.equal(result.exitCode, 0, describe(result));
  assert.match(result.stdout, /You win! Thanks for playing\./u);
  assert.doesNotMatch(result.stdout, /Out of attempts!/u, describe(result));
});

test("a game that never accepts an answer is rejected, bounded, without a win", async () => {
  const result = await play("never-wins", GAME_NEVER_WINS, { timeoutMs: 20_000 });
  assert.notEqual(result.exitCode, 0, describe(result));
  assert.doesNotMatch(result.stdout, /you win|correct/iu, describe(result));
  assert.equal(result.timedOut, false, describe(result));
  assert.ok(
    result.responses.length <= 60,
    `the driver must give up on inconsistent feedback: ${describe(result)}`,
  );
});

test("a program that never reads stdin is not driven at all", async () => {
  const result = await play("ignores-stdin", GAME_IGNORES_STDIN);
  assert.equal(result.exitCode, 0, describe(result));
  assert.deepEqual(result.responses, [], describe(result));
});

test("a program that prompts and then hangs is killed at the deadline", async () => {
  const startedAt = Date.now();
  const result = await play("hangs", GAME_HANGS, { timeoutMs: 6_000 });
  assert.equal(result.timedOut, true, describe(result));
  assert.notEqual(result.exitCode, 0, describe(result));
  assert.ok(Date.now() - startedAt < 20_000, "the deadline must bound the run");
});

test("a program that dies on start is reported red with its traceback", async () => {
  const result = await play("crashes", GAME_CRASHES);
  assert.equal(result.exitCode, 1, describe(result));
  assert.match(result.stderr, /Traceback \(most recent call last\):/u);
  assert.deepEqual(result.responses, [], describe(result));
});
